version: "3.8"

services:

  sl-api:
    container_name: sl-api
    build:
      context: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - strapi-lab-net
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=ysjfmVedKY+lTmClEyZnZA==,9mso9yBsV2CxXtZrHsfR9A==,WZsHRETBsKMeP/BZRyRYlg==,uzcPuLcSMj1z27XXDpnZ4Q==
      - API_TOKEN_SALT=ADfdCIWTW20I38dZ3WekFw==
      - ADMIN_JWT_SECRET=ZCKsPBuFr/3ZLWqdIGNadw==
      - TRANSFER_TOKEN_SALT=/jMQBWWMGSRC9IQMI26LJg==
      # Database
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=sl-postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=sl
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_SSL=false
      - JWT_SECRET=/GBlUdfAEMYiXU8ZFU3GAw==
      # Email
      - SMTP_HOST=localhost
      - SMTP_PORT=1035
      - SMTP_USERNAME=your_username
      - SMTP_PASSWORD=your_password
    ports:
      - '1337:1337'

  postgres:
    container_name: sl-postgres
    image: postgres
    env_file: backend/.env
    ports:
      - "6232:5432"
    networks:
      - strapi-lab-net
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sl"]
      interval: 5s
      timeout: 15s
      start_period: 10s
      retries: 10
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  mailhog:
    image: mailhog/mailhog
    container_name: "sl-mailhog"
    restart: always
    ports:
      - "8035:8025"
      - "1035:1025"

networks:
  strapi-lab-net:
    name: Strapi Lab Net
    driver: bridge
