version: "3.8"

services:

  backend:
    container_name: sl-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - backend/.env
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi-lab-net
    depends_on:
      - postgres
      - mailhog

  postgres:
    container_name: sl-postgres
    image: postgres
    ports:
      - "6232:5432"
    networks:
      - strapi-lab-net
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./backend/data/init-seed.sql:/docker-entrypoint-initdb.d/init-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sl"]
      interval: 5s
      timeout: 15s
      start_period: 10s
      retries: 10
    environment:
      - POSTGRES_DB=sl
      - POSTGRES_PASSWORD=postgres

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - strapi-lab-net

networks:
  strapi-lab-net:
    name: Strapi Lab Net
    driver: bridge
