version: "3.8"

services:

  postgres:
    container_name: sl-postgres
    image: postgres
    env_file: backend/.env
    ports:
      - "6232:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sl"]
      interval: 5s
      timeout: 15s
      start_period: 10s
      retries: 10
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  mailhog:
    image: mailhog/mailhog
    container_name: "sl-mailhog"
    restart: always
    ports:
      - "8035:8025"
      - "1035:1025"

